# Base Information
group_name: "OpenStudioLandscapes_RustDeskServer"
key_prefixes:
  - "OpenStudioLandscapes_RustDeskServer"

#compose_scope: "default"

#rustdeskserver_docker_image: "docker.io/rustdesk/rustdesk-server:latest"

# hbbs
#rustdeskserver_HBBS_ALWAYS_USE_RELAY: "Y"
#rustdeskserver_HBBS_WEB_CONSOLE_PORT_HOST: 21114  # Only in Pro version
#rustdeskserver_HBBS_WEB_CONSOLE_PORT_CONTAINER: "21114/tcp"  # Only in Pro version
#rustdeskserver_HBBS_NAT_TYPE_TEST_PORT_HOST: 21115
#rustdeskserver_HBBS_NAT_TYPE_TEST_PORT_CONTAINER: "21115/tcp"
#rustdeskserver_HBBS_ID_REGISTRATION_HEARTBEAT_TCP_PORT_HOST: 21116
#rustdeskserver_HBBS_ID_REGISTRATION_HEARTBEAT_TCP_PORT_CONTAINER: "21116/tcp"
#rustdeskserver_HBBS_ID_REGISTRATION_HEARTBEAT_UDP_PORT_HOST: 21116
#rustdeskserver_HBBS_ID_REGISTRATION_HEARTBEAT_UDP_PORT_CONTAINER: "21116/udp"
#rustdeskserver_HBBS_WEB_CLIENTS_SUPPORT_PORT_HOST: 21118  # Can be disabled if web clients are not needed
#rustdeskserver_HBBS_WEB_CLIENTS_SUPPORT_PORT_CONTAINER: "21118/tcp"  # Can be disabled if web clients are not needed

# hbbr
#rustdeskserver_HBBR_RELAY_SERVICES_PORT_HOST: 21117
#rustdeskserver_HBBR_RELAY_SERVICES_PORT_CONTAINER: "21117/tcp"
#rustdeskserver_HBBR_WEB_CLIENTS_SUPPORT_PORT_CONTAINER: 21119  # Can be disabled if web clients are not needed
#rustdeskserver_HBBR_WEB_CLIENTS_SUPPORT_PORT_HOST: "21119/tcp"  # Can be disabled if web clients are not needed

#rustdeskserver_data_store: "{DOT_LANDSCAPES}/{LANDSCAPE}/{FEATURE}/data"
